# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 01:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('FY', 'First Year'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], max_length=10)),
                ('major', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('sexualOrientation', models.CharField(choices=[('gay', 'Gay'), ('straight', 'Straight'), ('bisexual', 'Bisexual'), ('other', 'Other')], max_length=20)),
                ('bio', models.TextField()),
                ('idealDate', models.IntegerField(choices=[(1, 'Long walk on the beach'), (5, 'Cuddle in front of the fireplace with a glass of wine'), (10, 'Not really a date person')])),
                ('kagin', models.IntegerField(choices=[(1, 'Not really my scene'), (5, "I'll give it a try, but the pregame will probably be more fun"), (10, 'Lets do this thing.')])),
                ('cafemac', models.IntegerField(choices=[(1, 'North'), (4, 'East'), (6, 'West'), (10, 'South')])),
                ('athletes', models.IntegerField(choices=[(1, "Can't stand them"), (5, "They're alright"), (10, 'I love them')])),
                ('cold', models.IntegerField(choices=[(1, 'I love it'), (4, "It's not so bad"), (6, 'Not my favorite'), (10, 'Minnesota is hell on Earth')])),
                ('lookingFor', models.IntegerField(choices=[(1, 'Something a little more serious'), (4, 'Unsure'), (7, 'Repeated hookup'), (10, 'One night stand')])),
                ('politics', models.IntegerField(choices=[(1, 'Alt-Left'), (4, 'Fairly Left'), (6, 'Moderate'), (10, 'Mac GOP')])),
                ('aesthetics', models.IntegerField(choices=[(1, 'Pear'), (3, 'Grapefruit'), (5, 'Melon'), (8, 'Banana'), (10, 'Pineapple')])),
                ('nap', models.IntegerField(choices=[(1, 'Alone in my room'), (5, 'The library'), (10, 'Anywhere')])),
                ('saturday', models.IntegerField(choices=[(1, 'Attended a lecture'), (5, 'Went out with friends'), (10, "I don't remember")])),
                ('appSampler', models.IntegerField(choices=[(1, 'Fries'), (5, 'Mozzarella Sticks'), (10, 'Jalapeno Poppers')])),
                ('friendLookingFor', models.IntegerField(choices=[(1, 'A good friend'), (4, 'Unsure'), (7, 'Hang out occasionally'), (10, 'High five when drunk')])),
                ('score', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
