# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smack', '0002_remove_profile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
