# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smack', '0003_profile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sexualOrientation',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('bisexual', 'Bisexual'), ('other', 'Other')], max_length=20),
        ),
    ]
