# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smack', '0004_auto_20170414_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, upload_to='/uploads'),
        ),
    ]
