# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smack', '0005_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dislike',
            field=models.ManyToManyField(related_name='disliked_people', to='smack.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='like',
            field=models.ManyToManyField(related_name='liked_people', to='smack.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, max_length=200, upload_to=b'/Users/elevin/Documents/Macalester/Spring 2017/Internet Computing/FinalProject/doe/static'),
        ),
    ]
