# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smack', '0007_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='', max_length=200, upload_to='profilePics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
