# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smack', '0009_auto_20170501_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='disliked_people', to='smack.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_people', to='smack.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='profilePics'),
        ),
    ]
